### PR TITLE
WP-209: Fix the licenses given in Certificate Manager and keystore

### PR DESCRIPTION
**Pull request by jplyle**
http://jira.webinos.org/browse/WP-209

The licenses mentioned in package.json for the certificate manager and 
keystore are incorrect.  They have now been removed.

### CODE REVIEW

**Comment by ghost** [comment]
Why is the Merge commit there?

**Comment by jplyle** [comment]
I have absolutely no idea.  Creating this request involved more Git juju than I was happy with - I had to undo a load of my own pushes to my fork, rename branch, etc.  If you have any suggestions for how to get rid of it, I'd be very grateful.

**Comment by ghost** [comment]
I'll help you on skype later today (in about 1,5 hours) ;)

**Comment by ghost** [comment]
Its because you've already merged a branch and apparently deleted it. To fix:
1. git checkout the commit before these commits (b4127821ec365cc39667c9aaa562f9dc1e1c08bd)
2. Create branch with appropriate name
3. git checkout that branch
4. git cherry-pick the commit you need (9357fb989f119eb63beaee63aaaeccdf24b71b77)
5. git commit and git push and publish and whatever to get it on here
6. close this pull request and open a new one for that separate branch
7. delete the unnecessary commits by git checkout master and git reset hard for the commit before the wrong commits.

if it doesn't work, mail or skype :)

**Pull request closed without merging**
