### PR TITLE
Wp 449 : Session refactor work has broken widget server

### PR DESCRIPTION
**Pull request by TobyEalden**
http://jira.webinos.org/browse/WP-449

### CODE REVIEW

**Comment by habibvirji** [comment]
I think so that was not the idea. If you need to access ports then you can check pzp/userdara/pref.json

Exposing config will also include information a out the private  keys Id. Might be better if we can avoid accessing it all. 

Cheers
Habib Virji

**Comment by andreasbotsikas** [comment]
Then perhaps we need to expose the ports somehow from the pzp. Reading a file is not optimal as the port is already known to the pzp and it might be handy for other things too...

**Comment by andreasbotsikas** [comment]
btw, @TobyEalden these changes look like the ones I did besides the removal of the address (I didn't face the port shifting error), so you can cherrypick the rest of the changes and then work with the exposed ports, if this gets implemented.

**Comment by habibvirji** [comment]
That could be possible and perhaps something to add interface for. 

Cheers
Habib Virji

**Comment by andreasbotsikas** [comment]
@habibvirji  Should toby add the interface in the pzp? Expose a property with the websocket port? @TobyEalden can you add the property so that I merge this critical pull request?

**Comment by andreasbotsikas** [comment]
Also could you make sure that the webinos.js file uses the proper websocket port since you will be exposing it from the PZP?

**Comment by TobyEalden** [comment]
Yes - I'm on the case.

**Comment by TobyEalden** [comment]
OK, I've re-worked it to only expose the ports from the config.

**Pull request merged**
