### PR TITLE
WP-129 Improve the format of authentication codes

### PR DESCRIPTION
**Pull request by jplyle**
http://jira.webinos.org/browse/WP-129

This pull request changes the format of authentication codes (in line with webinos specs) to be
a three-byte value presented in upper-case hexadecimal format. 

The PZH server will automatically turn any lower-case inputs into upper-case.

JIRA: #WP-129

### CODE REVIEW

**Comment by andreasbotsikas** [comment]
@habibvirji  can you verify that this will not stop the auto-enrollment feature we have?

**Comment by jplyle** [comment]
@andreasbotsikas - I've tested auto-enrolment.  It still works under Linux, at least.

**Comment by jplyle** [comment]
Whoops, thanks to that rebase I've managed to remove some of the changes I made in a previous pull request.

Please don't approve this yet...

**Comment by habibvirji** [comment]
@andreas looks okay to me. Probably wait for rebase from John. 

Cheers
Habib Virji

**Pull request closed without merging**
