### PR TITLE
Add payment testing to webinos and enable payment service again

### PR DESCRIPTION
**Pull request by ChristianFuhrhop**
This puts the payment service back into webinos - it was
commented out of the code for some reason and never moved
to the github repository.
Add missing file webinos.payment.js from ancient checkout and
update to current calling conventions.
Fix of package.json, which had wrong service name.
Add testing script for payment API.
Include payment in build and running control files.

### CODE REVIEW

**Comment by habibvirji** [comment]
Can you please include "Jira issue: #ref", this should be last line in your commit and please provide Jira reference in your pull request

**Comment by ChristianFuhrhop** [comment]
On 25.07.2012 11:25, habibvirji wrote:

> Can you please include "Jira issue: #ref", this should be last line in your commit and please provide Jira reference in your pull request

Yes, I know that now. :-)

I did work on the code and the github commit first and created the Jira
issue afterwards (because that seemed like a 'normal' way of doing
things) and only realized at that point that I should have done so
before the commit.

Won't happen again.

Christian

**Comment by habibvirji** [comment]
No issues, can you update commit message using following three lines.
git reset --soft HEAD^ (This will remove that commit) 
git commit (Give new commit message with Jira Issue:#Ref) 
git push -f <local branch name>

Thanks and sorry for this trouble, as having this reference directly links jira issue. (I am just following https://developer.webinos.org/documentation/accepting-contributions-instructions-gatekeepers)

**Comment by ChristianFuhrhop** [comment]
Pull request closed, made two new commits and a new pull request, keeping same issue (WP-146)

**Pull request closed without merging**
