### PR TITLE
renamed apitests to monitortests

### PR DESCRIPTION
**Pull request by krishnabangalore**
jira issue: WP-268

renamed apitests to monitortests
and same changes in the client.html page too

### CODE REVIEW

**Comment by TobyEalden** [comment]
Don't see why the rename is necessary - monitortests doesn't really mean anything, whereas apitests describes it perfectly. Also, this will break the WRT as it links to these tests too. I can change the WRT but to me it's less descriptive.

**Comment by habibvirji** [comment]
@krishnabangalore please rebase your commit on latest master

**Comment by habibvirji** [comment]
@krishnabangalore please rebase your commit on latest master

**Comment by krishnabangalore** [comment]
rebase done

**Pull request merged**
