### PR TITLE
Removes the need of having grunt installed globally.

### PR DESCRIPTION
**Pull request by eelcocramer**
Recently grunt was added to package.json to improve the generation of webinos.js.

However this adds the dependency to have grunt installed globally. For platform developers this is probably no problem as they might want to generate the webinos.js as part of their development process anyway.

For users and app developers this adds another step to the installation of the webinos platform.

Accepting this pull removes the need of having grunt installed globally. IMO this would be an improvement.

Jira issue: WP-202

### CODE REVIEW

**Comment by aldafu** [comment]
I have some points about why I think installing grunt globally is okay:
- This change doesn't work on Windows.
- Installing grunt globally is recommended by the grunt project, prominently displayed on their homepage.
- Maybe it's a good idea to distribute webinos.js separately for app developers.

**Comment by aldafu** [comment]
Further this change will break building webinos.js for everybody that has grunt installed globally.

**Comment by eelcocramer** [comment]
> Further this change will break building webinos.js for everybody that has grunt installed globally.

I've tested that and it doesn't break in my configuration.

**Comment by eelcocramer** [comment]
> This change doesn't work on Windows.

I haven't tested this (I do not have windows available to me). If this is the case we should not pull.

**Pull request closed without merging**
