### PR TITLE
Replace webinos-gyp tool chain with node-gyp

### PR DESCRIPTION
**Pull request by andreasbotsikas**
In response to http://jira.webinos.org/browse/WP-73 I have removed the old gyp tools we had in order to move forward using  “node-gyp” to build native modules. The purpose of this changes is to unify the building instruction between *nix and windows.
Wscript files were not removed as npm supports them for the time being (another Jira issue will tackle with them). 
Refactored the simplenodemodule example to demonstrate the new way of building.
Renamed module.gyp files in policy_manager/promptMan. Keystore’s module.gyp file will be renamed in another pull request (already pending).

### CODE REVIEW

**Comment by ghost** [comment]
Jira issue is not referenced from the commits!
(Some summaries are too long as well, when you're rewriting the description, please consider limiting the first line to 50 characters so people can scan the history quickly, other stuff can come after the blank line. Example https://developer.webinos.org/git-commit-message-structure )

**Comment by habibvirji** [comment]
gyp folders should be kept in the tools directory. as gyp is not available for the mac platform, it might be good idea to keep it.

**Comment by andreasbotsikas** [comment]
gyp is bundled with node-gyp (https://github.com/TooTallNate/node-gyp/tree/master/legacy/tools/gyp)

**Comment by habibvirji** [comment]
Thanks was not aware about it.

**Comment by andreasbotsikas** [comment]
Setting the history right in another PR...

**Pull request closed without merging**
