### PR TITLE
WP 634 application policy creation

### PR DESCRIPTION
**Pull request by ccameroni**
http://jira.webinos.org/browse/WP-634

Translation from application manifest to policy.

### CODE REVIEW

**Comment by jplyle** [comment]
This looks good - but could @smonteleone or @steverc have a look and comment?

**Comment by smonteleone** [comment]
At a first look it seems good also for me.

Just a note: we should decide (maybe now is better) which is the "preferred" lib to convert XML to JSON.

Webinos-Platform/$ grep -iR "require(.xml2js" . | grep -v node_modules

./webinos/core/api/contacts/lib/google_contacts.js:         var xml2js = require('xml2js'); //XML parser
./webinos/core/api/mediacontent/lib/mediacontent.js:        var xml2js = require('xml2json'), result;
./webinos/core/manager/policy_manager/lib/policyeditor.js:  var xml2js = require('xml2js');
./webinos/core/manager/synchronisation_manager/index.js:    var xml2js = require('xml2json');

 @habibvirji @ccameroni @AndreaAtz @paolovergori @michelemorello  @steverc @jplyle

**Comment by jplyle** [comment]
Yes, if @habibvirji could confirm that this XML -> JSON conversion library is OK (as he knows the most about the module options) that would be great.

**Comment by habibvirji** [comment]
Yes xml2js is the XML to JSON library to use.

**Pull request merged**
