### PR TITLE
Fix exclusive file creation on Android (untested)

### PR DESCRIPTION
**Pull request by felixvisee**
Jira issue: WP-859

### CODE REVIEW

**Comment by felixvisee** [comment]
I'm very busy writing my master's thesis (14 days left). If someone could test this on Android, that would be awesome.

**Comment by paddybyers** [comment]
Yes, it's the same thing, but I was initially told that yours didn't work so I started changing it.

BTW I understand that the new excl flags don't work on OSX either, so this fix is maybe not as nasty as you think.

**Comment by mlasak** [comment]
Is this PR obsolete due to https://github.com/webinos/Webinos-Platform/pull/538 now?

**Comment by mlasak** [comment]
creating folders, files and removing works again on Android.

**Comment by paddybyers** [comment]
> Is this PR obsolete due to #538 now?

Yes

**Pull request closed without merging**
