### PR TITLE
Disable CRL list check on PZP

### PR DESCRIPTION
**Pull request by ziransun**
Jira Issue: WP-954

### CODE REVIEW

**Comment by jplyle** [comment]
Lets make sure that this change doesn't get propagated to the main codebase - we don't want to lose CRL checking altogether.

**Comment by ziransun** [comment]
Agreed. CRL checking should be performed. As discussed with Habib, we commented it out rather than removing it in the code so we can look at how to support overall CRL check later.

**Comment by habibvirji** [comment]
valid point... first we need to check at PZH end what's wrong with including CRL.. and then at PZP end. It just needs some testing and fixes...

**Comment by habibvirji** [comment]
Would prefer in following this up in modularized rather in living labs branch

**Comment by jplyle** [comment]
Yes, agreed.

**Pull request merged**
