### PR TITLE
Wp 836 android automated testing

### PR DESCRIPTION
**Pull request by nix4**
Adding support to run automated webinos testing on android. Currently, this is only supported on an emulator and the tests are limited to checking for successful build of webinos apk and installation on an emulator. The tests are part of npm test, but will not run on developer machines unless an environment variable "RUN_ANDROID_CI" = "yes" has been set.

### CODE REVIEW

**Comment by jplyle** [comment]
Looks good... except that there are merge conflicts.  Any chance you could rebase this against the current master?

Also - have you tested breaking something to see what happens?  e.g., breaking a line to stop the android build working?

Which Android API levels are you testing?

**Comment by nix4** [comment]
Ok. Will fix the conflicts.

If the ant build fails for any reason, then the tests will fail. The emulator may still run but will exit if installation of APK (which should not exist if ant build fails) fails. I will run some more tests on this.

I'm assuming Android API level 10. This can easily be changed in tools/android-ci/android-ci.js.

**Comment by nix4** [comment]
I have merged the changes from upstream. I tested breaking compilation of android code. This led to ant build failure which was caught in the CI tests.

**Comment by ziransun** [comment]
I had a run on my local machine following the instruction - only tested the success case. It seems working fine. 

This covers build and .apk install tests. For system test, e.g. running Android PZP and check services etc,  I guess that we are look separately.  I take you have already got plan in mind? :)

**Comment by nix4** [comment]
Yes, I'm currently working on running the PZP and checking whether that is successful (i.e using the event notification API).

**Comment by ziransun** [comment]
Any special test tools you are using?

**Comment by nix4** [comment]
Not. It's all node.js and a bit of shell (and off course android tools)

**Comment by jplyle** [comment]
Merged.  Many thanks, Cornelius!

**Pull request merged**
