### PR TITLE
Fix for the XMPP demo

### PR DESCRIPTION
**Pull request by eelcocramer**
Jira issue: WP-52

### CODE REVIEW

**Comment by ghost** [comment]
Commenting on here doesn't add the Jira issue: WP-52 to the commit message, so jira won't pick it up. You can change the commit message quickly by finding the hash of the commit just before the first you need to change and issue git rebase -i #hash and then changing pick to reword in the file opened, you can then change the messages one by one!

**Comment by eelcocramer** [comment]
Like this?

**Comment by ghost** [comment]
No, not exactly, now you have double commits and merge commits. This is exactly what needs to be avoided :)
I'll create instructions for rebasing and so on tomorrow. You can also mail me or add me on skype for more info.

**Comment by eelcocramer** [comment]
WIll create a new pull request for this.

**Pull request closed without merging**
