### PR TITLE
WP-349 messages schema check

### PR DESCRIPTION
**Pull request by ccameroni**
http://jira.webinos.org/browse/WP-349

### CODE REVIEW

**Comment by jplyle** [comment]
I'd like to merge this.  Travis CI doesn't appear to have triggered - any chance you could run 'npm test' and tell me the output?

Thanks.

**Comment by jplyle** [comment]
Actually, I've found it: https://travis-ci.org/webinos/Webinos-Platform/builds/6025836

There are lots of 'generic message validation failed' outputs - is this expected?

**Comment by ccameroni** [comment]
Yes it is expected. Those are outputs of tests on invalid messages

**Comment by jplyle** [comment]
Great.  I'm afraid I _just_ merged Mark's changes, which seem to have caused a conflict with this one.  It should be a one-line fix in auto-test.sh, any chance you could rebase?

**Comment by ccameroni** [comment]
Rebased

**Comment by jplyle** [comment]
Thanks.  I'm going to briefly do some testing, then I'll merge it.

**Comment by jplyle** [comment]
All my tests worked.  Thanks!

**Pull request merged**
