### PR TITLE
Fix jasmine tests for the certificate manager.

### PR DESCRIPTION
**Pull request by jplyle**
Note that the public key hash tests have been disabled due to them still failing.

http://jira.webinos.org/browse/WP-803

Jira issue: WP-803

### CODE REVIEW

**Comment by habibvirji** [comment]
Probably we should sync up as this issue is resolved in certificate manager already.

**Comment by jplyle** [comment]
@habibvirji - what's the update plan with modularisation?  E.g., we've pushed various changes to Webinos-Platform in the last week, will those make their way to the modularised version?

**Comment by habibvirji** [comment]
Yes it should be. It should be upto individual owners to do that.

**Comment by jplyle** [comment]
Sorry, I don't understand - do you mean "yes, you will need to update the modules yourself" or "yes, the modularisation work will automatically include updates to the main platform until a given date" ?

**Comment by habibvirji** [comment]
Yes you will need to update the modules yourself. There are too many
modules and I cannot do it alone. I will do it only for PZP, PZH and PZHWEB

**Pull request closed without merging**
