### PR TITLE
Turn on testing of the PZP under Linux for Travis CI.

### PR DESCRIPTION
**Pull request by jplyle**
The PZP was not being started as part of the Travis build system.

This PR may fail...

http://jira.webinos.org/browse/WP-937

Jira issue: WP-937

### CODE REVIEW

**Comment by jplyle** [comment]
I need to see the Travis output before this can potentially be merged...

**Comment by jplyle** [comment]
This is still blocked by: http://jira.webinos.org/browse/WP-794

**Comment by nix4** [comment]
For a start we could the event notification API to determine if PZP has started successfully. I'm currently implementing this for the emulator, which I think we can reuse.

**Comment by jplyle** [comment]
The problem at the moment, is that the PZP is failing silently on Travis, but not in reality.  It's something to do with webinos_config and generating certificates.  It's a pain to debug, though.

At the moment we have a single result returned when the PZP has started successfully.  A better test would happen later, though.

**Comment by habibvirji** [comment]
This error has been fixed in webinos-keyStorage

The problem is that gnome-keyring requires xwindows to show popup and on travis system this is not available. So when key is being fetched on linux system it is trying to open a login window and it fails. 

A work around that I have done is webinos-keyStorage has a config file where you can configure keyStorage or fs. If fs is set it will run on headless pzp system.. 

I am not sure what's the strategy but on modularise code you will not have this issue.

**Pull request closed without merging**
