### PR TITLE
Added binary option to make the platform globally installable by npm

### PR DESCRIPTION
**Pull request by eelcocramer**
Jira issue: WP-100

### CODE REVIEW

**Comment by habibvirji** [comment]
Can you please resubmit to the latest master changes

**Comment by eelcocramer** [comment]
Sure. I will do that next week.

**Comment by ghost** [comment]
@habibvirji It's rebase on top of master (not merge in master changes) -> cleaner commits

**Comment by habibvirji** [comment]
Sorry not sure about it then. I am back on 30. So if someone else can do it is good or else can fix after coming back. 

Cheers
Habib Virji

**Pull request closed without merging**
