### PR TITLE
Wp 80

### PR DESCRIPTION
**Pull request by ziransun**

### CODE REVIEW

**Comment by habibvirji** [comment]
since this pushes a big change in Android related to peer discovery. good to have more details in the pull request. Please include some description as details are also missing from jira issue.

**Comment by ghost** [comment]
Ziran,
this pull request is quite old and can't be merged automatically anymore. Could you rebase it on top of master so that can happen again.
Could you also re-read the instructions on this process, mainly about the pull requests. Habib is right about this PR not being in the right format (no description, no link to the jira issue, ...). The jira issue itself should also contain more information. The title is clear for you, but anybody else will need more info.

Thanks!

PS: it's jira with an a, not jire ;)

**Comment by ziransun** [comment]
Hi Dieter,

Do I need to open another jirA issue for this? Not sure I can have another pull request on this branch...

Thanks,

Ziran

**Comment by ghost** [comment]
Hi Ziran.

There's no need to create a new issue. I've noticed you marked it as resolved, but I've reopened it (marking it as resolved should be left to gatekeepers when they merge the issue)
You can re-use this branch by rebasing on top of master. The pull request will be updated automatically. See this tutorial: http://git-scm.com/book/ch3-6.html
If you are having issues, please contact me on skype :)

**Pull request closed without merging**
