### PR TITLE
Adds support for widget renderer to xmpp pzp

### PR DESCRIPTION
**Pull request by eelcocramer**
Jira-issue: WP-565

### CODE REVIEW

**Comment by TobyEalden** [comment]
I'm not sure you can add widget_manager to dependencies.json right now - it doesn't load properly on Windows due to the zipfile module.

**Comment by eelcocramer** [comment]
That not a problem. It does not add zipfile to the npm dependencies. It only allow other webinos modules to lookup the widget manager module using the webinos dependency mechanism.

**Comment by TobyEalden** [comment]
You're right, the pzp still loads if zipfile is missing, which is what I was worried about. However if I try to load the widget server after adding your find-dependencies changes I get an error:

[4.11.2012-15:12:15:796] info pzp_sessionHandling.js(518) [toby-Precision-M4400-32_Pzp]  initialized pzp
[Error: Cannot find 'dependencies.json']
Error: Cannot find 'dependencies.json'
    at findDependencies (/home/toby/dev/wp-428/node_modules/find-dependencies/find-dependencies.js:25:32)
    at /home/toby/dev/wp-428/node_modules/find-dependencies/find-dependencies.js:48:22
    at /home/toby/dev/wp-428/webinos/core/manager/widget_manager/lib/ui/routes/stores.js:7:46
    at Object.<anonymous> (/home/toby/dev/wp-428/webinos/core/manager/widget_manager/lib/ui/routes/stores.js:62:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)

**Comment by eelcocramer** [comment]
Strange. Are you trying on Linux or Windows? Also do you have the file <webinos-platform-home>/webinos/core/manager/widget_manager/dependencies.json that I added?

**Comment by eelcocramer** [comment]
Ok, I found the resolution for this. It has something to do with the files loading in the vm context. Should be fixed with latest commit.

**Pull request merged**
