### PR TITLE
WP-129: Improve authentication code format

### PR DESCRIPTION
**Pull request by jplyle**
http://jira.webinos.org/browse/WP-129

The authentication code is now smaller (3 not 8 bytes) and is
in HEX not BASE64.  This makes it easier to input on constrained
devices.

The code is now case-insensitive (always upper case) and the
webinos_pzp script will no longer append '=' to the end of it.

JIRA #WP-129

### CODE REVIEW

**Comment by jplyle** [comment]
Third time lucky?

**Comment by habibvirji** [comment]
Can you please last line in your commit msg ; Jira Issue: WP-129

**Comment by jplyle** [comment]
Only if you don't mind me adding a merge! I can't seem to do so otherwise.

**Comment by habibvirji** [comment]
Hi John,

On your local branch:
1. Do git reset --soft HEAD^1 (This will reset commit message)
2. Add all files again and your commit msg with the last line.
3. Push your changes, no need to create new PR, it will get into the same PR

Regards
Habib

**Comment by jplyle** [comment]
... Now I have 5 commits.  What should I be doing?

**Comment by habibvirji** [comment]
HEAD^5, will remove 5 commits but keep all the file changes. But committing
might be problem. If you are particular about keeping 5 commits then use
gitk, it opens up a GUI, select the code that you want in each commit. You
can commit smaller changes in each file. Bit painful but doable, let me
know if you need help.

**Pull request merged**
