### PR TITLE
Added *_NotImplemented classes for bluetooth and keystore

### PR DESCRIPTION
**Pull request by andreasbotsikas**
Added *_NotImplemented classes for bluetooth and keystore
Renamed module.gyp file in keystore to binding.gyp and updated it to look for the notimplemented version on window.
Discovery's binding must be updated after merging the wp-71 jira issue (https://github.com/webinos/Webinos-Platform/pull/38) .

### CODE REVIEW

**Comment by ghost** [comment]
What is the jira issue?

**Comment by habibvirji** [comment]
bluetooth binding.gyp with windows file name is missing.

**Comment by andreasbotsikas** [comment]
I was waiting for your pull request to get merged because you have changed it, as I saw...

**Comment by ghost** [comment]
You don't have to wait. Git is pretty good at "not having many conflicts". And if there are, you can rebase pretty easily (well, at least in theory) :)

**Comment by ghost** [comment]
So the question is: can this be merged, or should andreas add some stuff first?

**Comment by habibvirji** [comment]
Andreas needs to add windows bluetooth file in binding.gyp

**Comment by andreasbotsikas** [comment]
Redone the work in https://github.com/webinos/Webinos-Platform/pull/51 in order to modify the root binding.gyp file too

**Pull request closed without merging**
