### PR TITLE
WP-563 privacy policy development - Authorizations

### PR DESCRIPTION
**Pull request by ccameroni**
http://jira.webinos.org/browse/WP-563
Modification of the policy manager to manage data handling preferences (authorizations only)

### CODE REVIEW

**Comment by jplyle** [comment]
Hi Cesare, I've asked Shamal to have a quick review of the code.  He should get back to you soon.

**Comment by jplyle** [comment]
Tests seem to run.  I get some weird policy manager errors when I click 'always allow', but I suspect that might be unrelated (I'm testing on your branch, not merged with master).

[TypeError: Cannot read property 'policy-set' of undefined]
TypeError: Cannot read property 'policy-set' of undefined
    at data2xml.attrProp (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/webinos/core/manager/policy_manager/lib/policyeditor.js:113:21)
    at Parser.exports.Parser.Parser.parseString (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/xml2js/lib/xml2js.js:213:18)
    at Parser.EventEmitter.emit (events.js:93:17)
    at Object.exports.Parser.Parser.reset.saxParser.onerror (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/xml2js/lib/xml2js.js:100:24)
    at emit (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/sax/lib/sax.js:325:33)
    at error (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/sax/lib/sax.js:354:3)
    at strictFail (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/sax/lib/sax.js:369:22)
    at Object.write (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/sax/lib/sax.js:613:11)
    at Parser.exports.Parser.Parser.parseString (/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/xml2js/lib/xml2js.js:221:31)
    at Parser.__bind [as parseString](/home/johl/git-repos/webinos-prs/cesare/Webinos-Platform/node_modules/xml2js/lib/xml2js.js:6:61)

**Comment by failys** [comment]
I've been through the C++ code in this request.  I'm a bit worried that there might be a very real risk of memory leaks introduced by these changes.  Here are my specific comments:

== AuthorizationsSet.cpp ==

64: I think you can remove this line because child appears to have no life outside of the if block and, even if an exception was getting thrown here, you're not doing anything about it anyway.  Consequently, you should prefix 'child' in line 69 with TiXmlElement *

67 - 71:  
- It seems a bit odd that you're #defining PURPOSES_NUMBER, but it's somehow ok to strings like "AuthzUseForPurpose" and "Purpose" hard coded.  Maybe it's worth defining these as static const (or #defining them if you must) in AuthorizationSet.h
- Replace instances of (TiXmlElement *) with static_cast<TiXmlElement *>

97:  If you can, make 'it' a vector<bool:::const_iterator 

 == AuthorizationSet.h  ==

24:  Do you really need to #include IPolicyBase.h.  It might be worth trying to forward declare TiXmlElement and Request instead before or after line 71, i.e.

class TiXmlElement;
class Request;

 == DataHandlingPreferences.cpp  ==

24: You should add a member initialisation list to null authorizationsset and obligationsset before the constructor starts proper, i.e. add the below in line 25
: authorisationsset(0),obligationsset(0)
You can then remove lines 37 and 47 because these will become superfluous

27: Rename 'PolicyId' to 'policyId'

51:  Is there any reason why you aren't 'deleting' authorizationsset and obligationsset in the destructor.  I suspect that not doing this might cause a memory leak if you're not handing off the memory to another object 

 == Obligation.cpp  ==
26-30:  This commented out code should be removed.  If people want to know what the constructor might have been doing in the past/may do in the future, then they can check the revision history.

 == Obligation.h  ==
29-30:  Remove these lines for the reasons given above

 == ObligationSet.cpp  ==

32: The constructor is adding heap Obligation objects to obligation, but these are being deleted here in the destructor.  You need to iterate obligation and manually delete these otherwise ObligationsSet will leak memory

 == PolicyManager.cpp  ==
23: dhp should be nulled in the member initialiation list.  You also need to delete this if it's not null in the destructor (I don't see any destructor changes to this class in your pull request) 

26: null datahandlingpreferences in the member initialisation list

 == PolicySet.cpp  ==

24: Add a member initialisation list to set datahandling preferences to dhp, i.e. : datahandlingpreferences(dhp)
41, 49:  These two lines may well cause memory leaks.  For 41, you need to make sure you are deleting these DataHandlingPreferences when you are deleting dhp (in PolicyManager?).  For 49, you need to iterate over provisionalactions in the destructor to free up all the heap ProvisionalActions objects.

 ==  ProvisionalActions.cpp  ==

34: You should be iterating provisionalaction in the destructor to delete all the heap ProvisionalAction objects you created in the constructor.

 == Rule.cpp  ==

44: Are these heap ProvisionalActions objects being deleted in the destructor?

**Comment by ccameroni** [comment]
@jplyle 
At first glance the problem seems related to decisionstorage, I will take a deeper look into this.

@failys 
Thanks Shamal, I will fix these problems.

**Comment by ccameroni** [comment]
Last commits should fix problems pointed out by Shamal.
In AuthorizationsSet.h the forward declaration of TiXmlElement and Request doesn't work. I replaced IPolicybase.h inclusion with tinyxml.h and Request.h inclusion.

**Comment by ccameroni** [comment]
I tested policy manager on webinos master branch (without my modifications) and I ran into the same problem found by John, so it is not related to privacy policies code.
It seems to me this problem happens when selecting a permanent decision (allow always, deny always), but only from the second time forward, when decision storage tries to read decisionpermanent.xml.
I opened decisionpermanent.xlm and found js code instead of XACML, so I guess the problem is related to the generationd of this file.

**Comment by ccameroni** [comment]
Thanks Shamal, I replaced casts as you suggested

**Comment by jplyle** [comment]
Hi Cesare,

This looks OK.  A couple of questions/points:

(1) You should try and keep your git commit summaries < 72 characters.  The same is true for your other commits on other pull requests.  Doesn't matter this time around, but worth considering for future reference.

(2) You have a few merge commits from different branches (e.g., https://github.com/ccameroni/Webinos-Platform/commit/2a3045b4255a380308035cbecf8dca7928d09ced ).  What are these for?

Other than that, it should be OK.  I'll merge this soonish, after I check a few things.

Thanks.

**Comment by ccameroni** [comment]
1) I'm sorry, my future commit summaries will be shorter than 72 characters

2) ccameroni@c10df9f and ccameroni@391fd60 are merge from master branch.
ccameroni@2a3045b is a merge from WP-636 (pull request https://github.com/webinos/Webinos-Platform/pull/348) where I fixed policy rules in old PM jasmine tests. In WP-563 I added my new tests to the old ones, so WP-636 is necessary to have working tests.

The whole WP-563 is merged into WP-586 (pull request https://github.com/webinos/Webinos-Platform/pull/365) because obligations part to work needs authorizations part.

Thanks

**Pull request merged**
