### PR TITLE
Wp 250 fixes for multiple pzps

### PR DESCRIPTION
**Pull request by aldafu**
This fixes a few issues introduced with since the merge of the session changes in WP-250. It wasn't possible to run two PZPs on a single host. These two commits make that possible again, even though there is still work left to make it properly work again (see http://jira.webinos.org/browse/WP-467)

With these changes two PZPs can communicate with each other indirectly over the PZH.

Jira-issue: http://jira.webinos.org/browse/WP-250

### CODE REVIEW

**Comment by habibvirji** [comment]
That was intended as it is not useful. For development purpose might be useful but for zero conf it is not useful. It needs server to run at 8040. Plus identity to check should be not friendly name but instead device name. 

In webinosid last callback return was to set pzh name. 

Cheers
Habib Virji

**Comment by aldafu** [comment]
I'd argue that having it just for development purpose is immensely helpful.

How about this: The standard port is 8040. That is what you rely on for the zeroconf discovery, right? We could add an command line option which if given will cause the PZP to use a different port. That would make multiple PZPs on a single host work, even if it breaks zeroconf. But that's okay, because it will only happen when developing and when that option was given. That way we stay flexible.

What's left is that for the socket connection between the PZPs to work, we need to know which at which port it is actually listening, i.e. jira issue WP-467.

About the naming: The commit is okay, just the name of the command line option should be --device-name instead?

**Comment by habibvirji** [comment]
The first reason use different port. Second issue is pzp name. Pzp name if is equivalent to device name it will make messaging work. Friendly name was more for display purpose while device name for session and messaging. 

Cheers
Habib Virji

**Comment by aldafu** [comment]
> The first reason use different port.

Is that a yes to my proposal to try different ports if a certain command line option was set, e.g. --allow-custom-port?

> friendly name vs. device name

Is that a yes to my proposal to rename the --friendly-name option to --device-name?

**Comment by habibvirji** [comment]
I am okay with adding a extra option for development purpose to allow PZP run on same machine. 

Regarding device name, I would differ. Device name should match with os.hostname(), friendly name is of form PC or Mobile. So what I would suggest the extra option for development that you intend to create, if that option is set, set extra parameter for device name. Keep friendly name is separate it is just for display purpose, session and messaging will rely on device name.

Can you update the PR with latest changes.

**Comment by aldafu** [comment]
I'm opening a new pull request which bases these changes on a more recent master.

**Pull request closed without merging**
