### PR TITLE
Added missing jsormdb module

### PR DESCRIPTION
**Pull request by andreasbotsikas**
Jira issue: (WP-90)[http://jira.webinos.org/browse/WP-90]

### CODE REVIEW

**Comment by ruanxin** [comment]
Hi, andreasbotsikas,

When I setup all the environment of Webinos on my Ubuntu, and run webinos_pzh, it still says
 INFO: [RPC] Could not load module context with message: Error: Cannot find module 'JSORMDB'

and the complete log show in screen is like below:
ruan@ruan-VirtualBox:~/Webinos-Platform$ webinos_pzh
info config fetched key file @@ ruan-VirtualBox_PzhFarm_conn_key
info pzh_farm initialized at 127.0.0.1
INFO: [RPC] Adding handler: ServiceDiscovery
INFO: [RPC] Error: Cannot find module 'JSORMDB'
INFO: [RPC] Could not load module context with message: Error: Cannot find module 'JSORMDB'
INFO: [RPC] Adding handler: http://webinos.org/api/events
INFO: [RPC] Adding handler: http://webinos.org/api/test
INFO: [RPC] Adding handler: ServiceDiscovery
INFO: [RPC] Error: Cannot find module 'JSORMDB'
INFO: [RPC] Could not load module context with message: Error: Cannot find module 'JSORMDB'
INFO: [RPC] Adding handler: http://webinos.org/api/events
INFO: [RPC] Adding handler: http://webinos.org/api/test
info config fetched key file @@ ruan-VirtualBox_PzhFarm_ws_key
info config fetched key file @@ xinruan_conn_key
info config fetched key file @@ EthanX_conn_key
info pzh_farm started PZH ... xinruan
info config saved configuration file - ruan-VirtualBox_PzhFarm
info pzh_farm started PZH ... EthanX
info config saved configuration file - ruan-VirtualBox_PzhFarm
info pzh_webserver listening on 9000
info pzh_webserver http Server listening on 8900
******\* PZH FARM STARTED *******
the pzh can run, but due to the error, maybe some problem will happen when it related to the jsormdb module.

**Comment by ghost** [comment]
Hi ruanxin,

THis pull request is (and will remain) closed. If this issue re-occurs, I invite you to re-open it on our issue tracker (it should always be referenced in the Pull Request description): http://jira.webinos.org/browse/WP-90
Or you can open a new issue.

Kind regards,

Dieter

**Comment by andreasbotsikas** [comment]
Hi ruanxin,

 Have you tried the latest version? Jsormdb is not needed in the pzh and should not load there :) as far as I know there is going to be a major change in the context source during the next couple of days, so stay tuned just in case this is a slight glitch of the existing source code.

**Comment by ruanxin** [comment]
if it has a new version will be released, it's a good news! Btw, I checkout the 0.6.0 version, is it the latest?

**Comment by andreasbotsikas** [comment]
You should try cloning the repo directly. Have you checked the developer.webinos.org portal that has the installation instructions?

**Comment by ruanxin** [comment]
yes, I follow the instructions and I use git tag, and it has only 2 versions, 0.5 and 0.6.0. then I checkout the newer one. during the installation, it's no problem, just when I run pzh, it shows error info. But as you said the jsormdb is not needed in pzh, I think it should no problem then.

**Comment by andreasbotsikas** [comment]
Yes, most probably it's a leftover which is the exact reason why we had to revisit this piece of code. It will be out by the end of this month so stay tuned.

**Pull request merged**
