### PR TITLE
Fix Mork line continuation parsing

### PR DESCRIPTION
**Pull request by cbotsikas**
Fixed a bug reported for contacts API on windows where on local files (.mab) it would skip the 74th char.
The problems was traced on the contributed code MorkParser.

Jira-issue: WP-639

### CODE REVIEW

**Comment by mlasak** [comment]
Testing on Mac.

**Comment by cbotsikas** [comment]
On windows it's working with all 3 test mab files

**Comment by mlasak** [comment]
Tested on Mac with mab files created on Mac, Windows and Linux. Works.

**Comment by cbotsikas** [comment]
It's tested on linux too. works ok.

**Pull request merged**
