### PR TITLE
Wp 779 update to grunt 0.4

### PR DESCRIPTION
**Pull request by aldafu**
Add new task to wrap concatenated code, previous directives for that are
not supported with grunt 0.4. Add grunt modules to package.json.

Remember to switch to grunt 0.4 use:
$ npm uninstall -g grunt
$ npm install -g grunt-cli
$ npm install --save-dev # from webinos dir

Installation instructions on https://developer.webinos.org/ need to be updated as well.

Jira-issue: http://jira.webinos.org/browse/WP-779

### CODE REVIEW

**Comment by andreasbotsikas** [comment]
npm install -g grunt@0.3 is much better solution till we make sure that grunt serves our purposes.

I have updated the documentation to mark the specific grunt version

If it's worthy complicating the installation instructions, then we can merge

**Comment by aldafu** [comment]
The instructions I gave to install grunt 0.4 are actually only relevant to people who have had 0.3 installed before.

For new installations the instructions only change from:
npm install -g grunt
to:
npm install -g grunt-cli

**Comment by andreasbotsikas** [comment]
Great then. Can you also change the redundant cd webinos && grunt && cd... I don't think we need to traverse in the webinos folder now that the file is renamed, right?

Ps I got confused with the new --save-dev parameter which is proposed by grunt

**Comment by cbotsikas** [comment]
I think we also need to change lint because they have also changed lint to https://github.com/gruntjs/grunt-contrib-jshint plugin.

Do you know what's --save-dev all about?

If my PR get's merged to the concat plugin we will just have to add the following options inside concat:

```
      options: {
        banner: "<%= header %>",
        footer: "<%= footer %>"
      },
```

**Comment by aldafu** [comment]
Good call, fixed.

**Comment by cbotsikas** [comment]
http://gruntjs.com/upgrading-from-0.3-to-0.4#core-tasks-are-now-grunt-plugins here's more info about the lint

**Comment by cbotsikas** [comment]
I've read more about the --save-dev and i don't think we need it.
We should just keep it simple and move the packages back to the dependencies section skipping the --save-dev option.

http://stackoverflow.com/a/14953653
https://npmjs.org/doc/install.html

**Comment by aldafu** [comment]
Added the jshint task (which btw generates a huge output ;-). Also splitted the wrap task into its own commit, so we can revert that if we get the footer support from grunt later.

About --save-dev, using it is optional, running just "npm install" will still pull in all the dependencies including devDependencies. Having the grunt stuff in devDependencies is a bit cleaner IMO, since grunt isn't needed to run webinos, it's only needed for development. So I left that unchanged.

**Comment by andreasbotsikas** [comment]
Footer support added :)
https://github.com/gruntjs/grunt-contrib-concat/pull/10

**Comment by aldafu** [comment]
Updated to use new grunt-contrib-concat release with footer option.

**Comment by andreasbotsikas** [comment]
Nice work @aldafu

**Comment by habibvirji** [comment]
@andreasbotsikas  Just wondering should we merge this

**Comment by cbotsikas** [comment]
@habibvirji  I think we can.

**Comment by habibvirji** [comment]
@aldafu can you please update to latest master

**Comment by aldafu** [comment]
Are you getting a conflict? It merges fine for me onto latest master.

**Comment by habibvirji** [comment]
@aldafu Yes probably due to John changes in grunt.js might conflict with yours.

**Comment by aldafu** [comment]
ok, rebased it

**Comment by andreasbotsikas** [comment]
well done @aldafu! Thanks for updating the documentation too :)

**Comment by aldafu** [comment]
Thanks :-)

Andreas Botsikas notifications@github.com schrieb:

well done @aldafuhttps://github.com/aldafu! Thanks for updating the documentation too :)

**Pull request merged**
